// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               v5.29.1
// source: google/api/annotations.proto

/* eslint-disable */

export const protobufPackage = "google.api";
