// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               v3.21.3
// source: cosmos/query/v1/query.proto

/* eslint-disable */

export const protobufPackage = "cosmos.query.v1";
